name: Syncing github:zen-browser/desktop/tree/dev/src/zen/@types

on:
  schedule:
    - cron: '0 0 * * *'

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: checkout our repo.
        uses: actions/checkout@v4
        with:
          path: output
          token: ${{ secrets.PAT }}
          
      - name: checkout zen repo.
        uses: actions/checkout@v4
        with:
          repository: zen-browser/desktop
          ref: dev
          path: source
          sparse-checkout: |
            src/zen/@types
      
      - name: check for update and perform sync
        run: |
          rsync -av --delete source/src/zen/@types/* output/
          cd output/
          if git status --porcelain | grep -q .; then
            echo "Changes detected, committing and pushing..."
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "auto-sync: updates from zen-browser/desktop"
            git push origin main
          else
            echo "No changes detected in types directory."
          fi
